added seccomp=unconfined for cassandra containers
- this is needed for nodemgr to allow podman exec
to cassandra containers
Otherwise it fails with
Error: exec failed: container_linux.go:349: starting
container process caused "error adding seccomp rule
for syscall socket: requested action matches default
action of filter": OCI runtime error

closes-jira-bug: CEM-23912
Change-Id: I188c94df7d507d9061319353d56ff23f0e66a949